### ISSUE TITLE
Dropdown button always is open

### ISSUE THREAD

**Issue by sezaru** [petalframework/petal_components#146]
I'm using petal_components 1.0.2 and liveview 0.18.16

I added the following dropdown to my HTML:

```elixir
  <.dropdown>
    <.dropdown_menu_item label="Item 1" />
    <.dropdown_menu_item label="Item 2" />
  </.dropdown>
```

But the dropdown will always show as open, and I can't close it in any way:

![image](https://user-images.githubusercontent.com/279828/221259205-86ee8713-2f8e-4df7-844d-f2216643939b.png)

**Comment by sezaru** [comment]
Just an update, I noticed the exact same problem when using an accordion

**Comment by mplatts** [comment]
I'm guessing it's an Alpine JS issue. But I now realise I haven't put this in the install docs... I'm amazed it's taken this long for an issue to appear.

We use alpine JS out of the box (though you can pass `<.dropdown js_lib="live_view_js"...` if you're working in a live environment.

So in your head you need to load Alpine JS:

```html
<script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
```

And in your CSS you need:

```css
/* Add this to AlpineJS elements that start off hidden. When AlpineJS is loaded it will remove all x-cloak attributes */
  [x-cloak=""] {
    display: none;
  }
```

I'll update the install docs now. And will add that CSS to default.css so people don't have to worry about manually adding it.
